# Generated by Django 4.2 on 2024-01-20 20:04

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True)),
                ('age_from_week', models.PositiveIntegerField(blank=True, null=True)),
                ('age_to_week', models.PositiveBigIntegerField(blank=True, null=True)),
                ('formula_basis', models.CharField(blank=True, choices=[('AF', 'As-Fed Basis'), ('DM', 'DM Basis')], default=None, max_length=4, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('desired_ratio', models.DecimalField(blank=True, decimal_places=3, default=100, max_digits=15, null=True)),
                ('desired_dm', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('ration_price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('ration_ratio', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('ration_weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('ration_dm', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormulaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ration', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('min', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaRation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFormula',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True)),
                ('age_from_week', models.PositiveIntegerField(blank=True, null=True)),
                ('age_to_week', models.PositiveBigIntegerField(blank=True, null=True)),
                ('formula_basis', models.CharField(blank=True, choices=[('AF', 'As-Fed Basis'), ('DM', 'DM Basis')], default=None, max_length=4, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('desired_ratio', models.DecimalField(blank=True, decimal_places=3, default=100, max_digits=15, null=True)),
                ('desired_dm', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('ration_price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('ration_ratio', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('ration_weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('ration_dm', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical formula',
                'verbose_name_plural': 'historical formulas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormulaIngredient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ration', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('min', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical formula ingredient',
                'verbose_name_plural': 'historical formula ingredients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormulaRation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical formula ration',
                'verbose_name_plural': 'historical formula rations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormulaRequirement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical formula requirement',
                'verbose_name_plural': 'historical formula requirements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
