# Generated by Django 4.2 on 2023-07-30 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrients', '0003_nutrientgroup_created_at_nutrientgroup_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0012_alter_ingredient_nutrients'),
        ('purposes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormulaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.formula')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormulaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ratio_min', models.FloatField(default=0, null=True)),
                ('ratio_max', models.FloatField(default=0, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.formula')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formula',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, through='formulas.FormulaIngredient', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='formula',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purposes.purpose'),
        ),
        migrations.AddField(
            model_name='formula',
            name='requirements',
            field=models.ManyToManyField(blank=True, null=True, through='formulas.FormulaRequirement', to='nutrients.nutrient'),
        ),
    ]
