# Generated by Django 4.2 on 2024-01-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirements', '0002_initial'),
        ('purposes', '0002_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('formulas', '0001_initial'),
        ('ingredients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalformularequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformularequirement',
            name='formula',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='historicalformularequirement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformularequirement',
            name='nutrient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='historicalformularation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformularation',
            name='formula',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='historicalformularation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformularation',
            name='nutrient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='historicalformulaingredient',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformulaingredient',
            name='formula',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='historicalformulaingredient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformulaingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='historicalformula',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='historicalformula',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformula',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformula',
            name='purpose',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purposes.purpose'),
        ),
        migrations.AddField(
            model_name='historicalformula',
            name='requirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='formularequirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formularequirement',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='formularequirement',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='formularation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formularation',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='formularation',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='formulaingredient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulaingredient',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='formulaingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='formula',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='formula',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formula',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, through='formulas.FormulaIngredient', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='formula',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purposes.purpose'),
        ),
        migrations.AddField(
            model_name='formula',
            name='rations',
            field=models.ManyToManyField(blank=True, null=True, related_name='formula_rations', through='formulas.FormulaRation', to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='formula',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='formula',
            name='requirements',
            field=models.ManyToManyField(blank=True, null=True, related_name='formula_requirements', through='formulas.FormulaRequirement', to='nutrients.nutrient'),
        ),
        migrations.AlterUniqueTogether(
            name='formularequirement',
            unique_together={('formula', 'nutrient')},
        ),
        migrations.AlterUniqueTogether(
            name='formularation',
            unique_together={('formula', 'nutrient')},
        ),
        migrations.AlterUniqueTogether(
            name='formulaingredient',
            unique_together={('formula', 'ingredient')},
        ),
    ]
