# Generated by Django 4.2 on 2023-07-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
