# Generated by Django 4.2 on 2023-08-23 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0005_formula_age_from_week_formula_age_to_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='desired_dm',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='formula',
            name='desired_ratio',
            field=models.DecimalField(decimal_places=5, default=100, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='formula',
            name='ration_dm',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='formula',
            name='ration_ratio',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
