# Generated by Django 4.2 on 2023-08-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0006_alter_formula_desired_dm_alter_formula_desired_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
    ]
