# Generated by Django 4.2 on 2023-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0008_alter_formulaingredient_ratio_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='budget_currency',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='ration_price_currency',
        ),
        migrations.AddField(
            model_name='formula',
            name='ration_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='ration_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='formularation',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='formularequirement',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
    ]
