# Generated by Django 4.2 on 2023-10-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0010_alter_formula_desired_dm_alter_formula_desired_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='weight_unit',
        ),
    ]
