# Generated by Django 4.2 on 2023-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0014_historicalformularequirement_historicalformularation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalformula',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
