# Generated by Django 4.2 on 2023-12-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_historicalrequirementnutrient'),
        ('formulas', '0016_remove_formulaingredient_ratio_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='historicalformula',
            name='requirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requirements.requirement'),
        ),
    ]
