# Generated by Django 4.2 on 2023-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0017_formula_requirement_historicalformula_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='desired_dm',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='desired_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, default=100, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='ration_dm',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='formula',
            name='ration_ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='formulaingredient',
            name='ration',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformula',
            name='desired_dm',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformula',
            name='desired_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, default=100, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformula',
            name='ration_dm',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicalformula',
            name='ration_ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicalformulaingredient',
            name='ration',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
