# Generated by Django 4.2 on 2024-02-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_historicalstage_description_historicalstage_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ('order',)},
        ),
    ]
