# Generated by Django 4.2 on 2023-11-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_historicalfarm'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='farm',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalfarm',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
