# Generated by Django 4.2 on 2024-02-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('processing_initiated', models.DateTimeField(blank=True, default=None, null=True)),
                ('format', models.CharField(max_length=255, verbose_name='Format of file to be imported')),
                ('errors', models.TextField(blank=True, default='', verbose_name='Errors')),
                ('resource', models.CharField(max_length=160, verbose_name='Name of resource to import to')),
                ('job_status', models.CharField(blank=True, choices=[('START', 'Starting'), ('DRY_RUN', 'Dry Run'), ('IMPORTING', 'Importing'), ('ERROR', 'Error'), ('DONE', 'Done')], max_length=160, verbose_name='Status of the job')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
    ]
