# Generated by Django 4.2 on 2024-03-11 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0002_initial'),
        ('import_export_job', '0004_alter_importjob_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('processing_initiated', models.DateTimeField(blank=True, default=None, null=True)),
                ('resource', models.CharField(max_length=160, verbose_name='Name of resource to export to')),
                ('format', models.CharField(max_length=255, verbose_name='Format of file to be imported')),
                ('job_status', models.CharField(blank=True, choices=[('START', 'Starting'), ('EXPORTING', 'Exporting'), ('ERROR', 'Error'), ('DONE', 'Done')], max_length=160, verbose_name='Status of the job')),
                ('email_on_completion', models.BooleanField(default=True, verbose_name='Send me an email when this export job is complete')),
                ('process_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
            options={
                'ordering': ('-process_finished',),
            },
        ),
    ]
