# Generated by Django 4.2 on 2024-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_job', '0005_exportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='errors',
            field=models.TextField(blank=True, default='', verbose_name='Errors'),
        ),
    ]
