# Generated by Django 4.2 on 2024-04-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_job', '0008_alter_exportjob_file_alter_importjob_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
