# Generated by Django 4.2 on 2024-04-08 12:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_job', '0009_alter_exportjob_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='./apidata/importdata'), upload_to=''),
        ),
    ]
