# Generated by Django 4.2 on 2023-08-07 16:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_rename_ratio_unitconverter_factor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breeds', '0002_breed_hdep_desirable_avg_breed_hhep_desirable_avg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedWeightGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.FloatField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breeds.breed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('weight_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='BreedEggGuid',
            new_name='BreedEggGuide',
        ),
        migrations.RenameModel(
            old_name='BreedHDEPGuid',
            new_name='BreedHDEPGuide',
        ),
        migrations.RenameModel(
            old_name='BreedHHEPGuid',
            new_name='BreedHHEPGuide',
        ),
        migrations.DeleteModel(
            name='BreedWeightGuid',
        ),
    ]
