"use client";

import SidebarMenu from "@/components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import { ProSidebarProvider, useProSidebar } from "react-pro-sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ProSidebarProvider>
        <body className={inter.className}>
          <div style={{ height: "100vh", display: "flex" }}>
            <SidebarMenu />
            <div style={{ overflowY: "scroll", width: "100%" }}>
              <Navbar />
              <div style={{ padding: "50px" }}>{children}</div>
            </div>
          </div>
        </body>
      </ProSidebarProvider>
    </html>
  );
}
