# Generated by Django 4.2 on 2024-01-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flocks', '0001_initial'),
        ('accusation', '0002_initial'),
        ('chickens', '0002_initial'),
        ('breeds', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalflockaccusation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalflockaccusation',
            name='flock',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='historicalflockaccusation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalflock',
            name='breed',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='breeds.breed'),
        ),
        migrations.AddField(
            model_name='historicalflock',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalflock',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flockreduction',
            name='chickens',
            field=models.ManyToManyField(blank=True, null=True, related_name='flock_reduction', to='chickens.chicken'),
        ),
        migrations.AddField(
            model_name='flockreduction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flockreduction',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='flockaccusation',
            name='accusation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accusation.accusation'),
        ),
        migrations.AddField(
            model_name='flockaccusation',
            name='chickens',
            field=models.ManyToManyField(blank=True, null=True, related_name='flock_accusation', to='chickens.chicken'),
        ),
        migrations.AddField(
            model_name='flockaccusation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flockaccusation',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accusations', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='flock',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeds.breed'),
        ),
        migrations.AddField(
            model_name='flock',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
