# Generated by Django 4.2 on 2023-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0002_historicalflock'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='no_chickens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalflock',
            name='no_chickens',
            field=models.IntegerField(default=0),
        ),
    ]
