# Generated by Django 4.2 on 2023-08-05 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_breed_hdep_desirable_avg_breed_hhep_desirable_avg_and_more'),
        ('chickens', '0004_chicken_flock_chicken_house_chicken_pen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accusation', '0001_initial'),
        ('flocks', '0004_flock_accusation_flock_accusation_date_flock_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flockreduction',
            old_name='no_chickens',
            new_name='no_chicken',
        ),
        migrations.RemoveField(
            model_name='flock',
            name='accusation',
        ),
        migrations.RemoveField(
            model_name='flock',
            name='accusation_date',
        ),
        migrations.RemoveField(
            model_name='flock',
            name='no_chickens',
        ),
        migrations.RemoveField(
            model_name='historicalflock',
            name='accusation',
        ),
        migrations.RemoveField(
            model_name='historicalflock',
            name='accusation_date',
        ),
        migrations.RemoveField(
            model_name='historicalflock',
            name='no_chickens',
        ),
        migrations.AddField(
            model_name='flock',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeds.breed'),
        ),
        migrations.AddField(
            model_name='flockreduction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flockreduction',
            name='reason',
            field=models.CharField(blank=True, choices=[('C', 'Cull'), ('D', 'Death'), ('S', 'Sold'), ('L', 'Lost'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalflock',
            name='breed',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='breeds.breed'),
        ),
        migrations.CreateModel(
            name='HistoricalFlockAccusation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accusation_date', models.DateField(blank=True, null=True)),
                ('no_chicken', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('accusation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accusation.accusation')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flocks.flock')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical flock accusation',
                'verbose_name_plural': 'historical flock accusations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FlockAccusation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accusation_date', models.DateField(blank=True, null=True)),
                ('no_chicken', models.PositiveIntegerField()),
                ('accusation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accusation.accusation')),
                ('chickens', models.ManyToManyField(blank=True, null=True, related_name='flock_accusation', to='chickens.chicken')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accusations', to='flocks.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
