# Generated by Django 4.2 on 2023-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0005_rename_no_chickens_flockreduction_no_chicken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flockaccusation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flockreduction',
            name='reduction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalflockaccusation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flockreduction',
            name='reason',
            field=models.CharField(blank=True, choices=[('C', 'Cull'), ('D', 'Death'), ('S', 'Sold'), ('L', 'Lost'), ('T', 'Tagged'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
    ]
