# Generated by Django 4.2 on 2024-01-20 20:04

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hatchery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('incubation_moved_date', models.DateField(blank=True, null=True)),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HatcheryEgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('no_eggs', models.IntegerField()),
                ('canndle_date', models.DateField(blank=True, null=True)),
                ('candled_eggs', models.IntegerField(blank=True, null=True)),
                ('infertile_egg', models.IntegerField(blank=True, null=True)),
                ('no_of_hatched', models.IntegerField(blank=True, null=True)),
                ('no_dead', models.IntegerField(blank=True, null=True)),
                ('no_culled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalHatchery',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('incubation_moved_date', models.DateField(blank=True, null=True)),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical hatchery',
                'verbose_name_plural': 'historical hatcherys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHatcheryEgg',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('no_eggs', models.IntegerField()),
                ('canndle_date', models.DateField(blank=True, null=True)),
                ('candled_eggs', models.IntegerField(blank=True, null=True)),
                ('infertile_egg', models.IntegerField(blank=True, null=True)),
                ('no_of_hatched', models.IntegerField(blank=True, null=True)),
                ('no_dead', models.IntegerField(blank=True, null=True)),
                ('no_culled', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical hatchery egg',
                'verbose_name_plural': 'historical hatchery eggs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIncubation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('temperature_celsius', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('humidity_fahrenheit', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('humidity_percent', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('remark', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical incubation',
                'verbose_name_plural': 'historical incubations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('temperature_celsius', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('humidity_fahrenheit', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('humidity_percent', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
