# Generated by Django 4.2 on 2024-01-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breeds', '0002_initial'),
        ('hatchery', '0001_initial'),
        ('eggs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incubation',
            name='hatchery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatchery_incubation', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='historicalincubation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalincubation',
            name='hatchery',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='historicalincubation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhatcheryegg',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhatcheryegg',
            name='egg',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='eggs.egg'),
        ),
        migrations.AddField(
            model_name='historicalhatcheryegg',
            name='hatchery',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='historicalhatcheryegg',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='breed',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='breeds.breed'),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hatcheryegg',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hatcheryegg',
            name='egg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatchery_eggs', to='eggs.egg'),
        ),
        migrations.AddField(
            model_name='hatcheryegg',
            name='hatchery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatchery_eggs', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='hatchery',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeds.breed'),
        ),
        migrations.AddField(
            model_name='hatchery',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
