# Generated by Django 4.2 on 2023-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatchery',
            name='hatchery_date',
        ),
        migrations.RemoveField(
            model_name='historicalhatchery',
            name='hatchery_date',
        ),
        migrations.AddField(
            model_name='hatchery',
            name='hatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hatchery',
            name='incubation_moved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='hatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='incubation_moved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hatcheryegg',
            name='candled_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hatcheryegg',
            name='canndle_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
