# Generated by Django 4.2 on 2024-02-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_alter_stage_options'),
        ('chickens', '0002_initial'),
        ('hatchery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchery',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_selection', to='stages.stage'),
        ),
        migrations.AddField(
            model_name='hatchery',
            name='selected_chickens',
            field=models.ManyToManyField(blank=True, null=True, related_name='selected_selection', to='chickens.chicken'),
        ),
        migrations.AddField(
            model_name='hatchery',
            name='selected_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='moved_to', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='hatchery',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection', to='stages.stage'),
        ),
        migrations.AddField(
            model_name='hatchery',
            name='unselected_chickens',
            field=models.ManyToManyField(blank=True, null=True, related_name='unselected_selection', to='chickens.chicken'),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='from_stage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stages.stage'),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='stage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stages.stage'),
        ),
    ]
