# Generated by Django 4.2 on 2024-02-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reduction_reason', '0002_initial'),
        ('hatchery', '0003_hatchery_from_stage_hatchery_selected_chickens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchery',
            name='generation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hatchery',
            name='reduction_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection', to='reduction_reason.reductionreason'),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='generation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='reduction_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reduction_reason.reductionreason'),
        ),
    ]
