# Generated by Django 4.2 on 2024-02-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0004_hatchery_generation_hatchery_reduction_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchery',
            name='reduction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='reduction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
