# Generated by Django 4.2 on 2024-03-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0005_hatchery_reduction_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hatchery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hatcheryegg',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='incubation',
            options={'ordering': ['-created_at']},
        ),
    ]
