# Generated by Django 4.2 on 2024-04-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0006_alter_hatchery_options_alter_hatcheryegg_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatchery',
            name='from_stage',
        ),
        migrations.RemoveField(
            model_name='hatchery',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='hatchery',
            name='reduction_date',
        ),
        migrations.RemoveField(
            model_name='hatchery',
            name='reduction_reason',
        ),
        migrations.RemoveField(
            model_name='hatchery',
            name='selected_chickens',
        ),
        migrations.RemoveField(
            model_name='hatchery',
            name='selected_from',
        ),
        migrations.RemoveField(
            model_name='hatchery',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='hatchery',
            name='unselected_chickens',
        ),
        migrations.RemoveField(
            model_name='historicalhatchery',
            name='from_stage',
        ),
        migrations.RemoveField(
            model_name='historicalhatchery',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='historicalhatchery',
            name='reduction_date',
        ),
        migrations.RemoveField(
            model_name='historicalhatchery',
            name='reduction_reason',
        ),
        migrations.RemoveField(
            model_name='historicalhatchery',
            name='stage',
        ),
    ]
