# Generated by Django 4.1.7 on 2023-03-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_remove_feed_date_remove_historicalfeed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='feeds.feedtype'),
        ),
    ]
