# Generated by Django 4.2 on 2024-01-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirements', '0001_initial'),
        ('ingredients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementnutrient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='requirementnutrient',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='requirementingredient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='requirementingredient',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirement',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='requirement_ingredients', through='requirements.RequirementIngredient', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='nutrients',
            field=models.ManyToManyField(blank=True, null=True, related_name='requirement_nutrients', through='requirements.RequirementNutrient', to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='historicalrequirementnutrient',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrequirementnutrient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrequirementnutrient',
            name='nutrient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='historicalrequirementnutrient',
            name='requirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='historicalrequirementingredient',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrequirementingredient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrequirementingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='historicalrequirementingredient',
            name='requirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='historicalrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrequirement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='requirementnutrient',
            unique_together={('requirement', 'nutrient')},
        ),
        migrations.AlterUniqueTogether(
            name='requirementingredient',
            unique_together={('requirement', 'ingredient')},
        ),
    ]
