# Generated by Django 4.2 on 2023-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_historicalrequirement_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequirement',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
    ]
