# Generated by Django 4.2 on 2023-10-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0004_nutrient_created_at_nutrient_created_by_and_more'),
        ('requirements', '0003_historicalrequirement_weight_requirement_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirementnutrient',
            options={'ordering': ['nutrient']},
        ),
        migrations.AlterUniqueTogether(
            name='requirementnutrient',
            unique_together={('requirement', 'nutrient')},
        ),
    ]
