# Generated by Django 4.2 on 2023-12-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0022_historicalingredient_max_historicalingredient_min_and_more'),
        ('requirements', '0006_historicalrequirementingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='requirement_ingredients', through='requirements.RequirementIngredient', to='ingredients.ingredient'),
        ),
    ]
