# Generated by Django 4.2 on 2023-12-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_requirement_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequirement',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
