# Generated by Django 4.1.7 on 2023-03-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='total_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalegg',
            name='total_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
