# Generated by Django 4.2 on 2024-01-20 20:04

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.CharField(max_length=250, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True)),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('reduction_date', models.DateField(blank=True, null=True)),
                ('generation', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(max_length=250)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree_source', to='chickens.chicken')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree_target', to='chickens.chicken')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalChicken',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.CharField(db_index=True, max_length=250)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True)),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('reduction_date', models.DateField(blank=True, null=True)),
                ('generation', models.PositiveIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('breed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='breeds.breed')),
            ],
            options={
                'verbose_name': 'historical chicken',
                'verbose_name_plural': 'historical chickens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
