# Generated by Django 4.2 on 2023-07-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicken',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='chicken',
            name='sire',
        ),
        migrations.RemoveField(
            model_name='historicalchicken',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='historicalchicken',
            name='sire',
        ),
    ]
