# Generated by Django 4.2 on 2024-02-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='color',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='color',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterModelOptions(
            name='chicken',
            options={'ordering': ['-created_at']},
        ),
    ]
