# Generated by Django 4.2 on 2024-04-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
        ('chickens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chickens', to='houses.house'),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='house',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='houses.house'),
        ),
    ]
