# Generated by Django 4.2 on 2024-04-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0003_chicken_house_historicalchicken_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='color',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='color',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
