# Generated by Django 4.2 on 2023-08-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('flocks', '0004_flock_accusation_flock_accusation_date_flock_note_and_more'),
        ('chickens', '0003_chicken_dam_chicken_sire_historicalchicken_dam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='chicken',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='houses.house'),
        ),
        migrations.AddField(
            model_name='chicken',
            name='pen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='flock',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='house',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='houses.house'),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='pen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
