# Generated by Django 4.2 on 2024-03-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0003_chicken_color_historicalchicken_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chicken',
            options={'ordering': ['-created_at']},
        ),
    ]
