# Generated by Django 4.2 on 2023-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0004_chicken_flock_chicken_house_chicken_pen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='reduction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chicken',
            name='reduction_reason',
            field=models.CharField(blank=True, choices=[('C', 'Cull'), ('D', 'Death'), ('S', 'Sold'), ('L', 'Lost'), ('T', 'Tagged'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='reduction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='reduction_reason',
            field=models.CharField(blank=True, choices=[('C', 'Cull'), ('D', 'Death'), ('S', 'Sold'), ('L', 'Lost'), ('T', 'Tagged'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
    ]
