# Generated by Django 4.2 on 2023-10-18 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reduction_reason', '0001_initial'),
        ('chickens', '0005_chicken_reduction_date_chicken_reduction_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='reduction_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='reduction_reason.reductionreason'),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='reduction_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reduction_reason.reductionreason'),
        ),
    ]
