# Generated by Django 4.2 on 2023-11-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0006_alter_chicken_reduction_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='generation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='generation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(max_length=250)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree_source', to='chickens.chicken')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree_target', to='chickens.chicken')),
            ],
        ),
    ]
