# Generated by Django 4.2 on 2023-11-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0007_chicken_generation_historicalchicken_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='hatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='hatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
