# Generated by Django 4.2 on 2023-11-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0003_historicalhatcheryegg'),
        ('chickens', '0008_chicken_hatch_date_historicalchicken_hatch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicken',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='chicken',
            name='house',
        ),
        migrations.RemoveField(
            model_name='historicalchicken',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='historicalchicken',
            name='house',
        ),
        migrations.AddField(
            model_name='chicken',
            name='hatchery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='hatchery',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hatchery.hatchery'),
        ),
    ]
