# Generated by Django 4.2 on 2023-11-07 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
        ('chickens', '0009_remove_chicken_flock_remove_chicken_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='pen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chickens', to='pen.pen'),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='pen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pen.pen'),
        ),
    ]
