# Generated by Django 4.2 on 2023-11-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0006_rename_breedhdepguide_breedhdepguideline_and_more'),
        ('chickens', '0010_alter_chicken_pen_alter_historicalchicken_pen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeds.breed'),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='breed',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='breeds.breed'),
        ),
    ]
