# Generated by Django 4.2 on 2023-06-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='farms',
            field=models.ManyToManyField(blank=True, to='farms.farm'),
        ),
    ]
