# Generated by Django 4.2 on 2023-05-14 17:33

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='farm',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='farms.farm'),
        ),
    ]
