# Generated by Django 4.2 on 2023-06-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_city_farm_country_farm_email_farm_phone_number_and_more'),
        ('users', '0004_alter_user_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='farm',
        ),
        migrations.AddField(
            model_name='user',
            name='farms',
            field=models.ManyToManyField(to='farms.farm'),
        ),
    ]
