# Generated by Django 4.2 on 2023-06-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_city_farm_country_farm_email_farm_phone_number_and_more'),
        ('users', '0005_remove_user_farm_user_farms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='farms',
            field=models.ManyToManyField(blank=True, null=True, to='farms.farm'),
        ),
    ]
