# Generated by Django 4.2 on 2024-03-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrientgroup',
            options={'ordering': ['-created_at']},
        ),
    ]
