# Generated by Django 4.2 on 2023-11-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0004_nutrient_created_at_nutrient_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnutrient',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
