# Generated by Django 4.2 on 2023-12-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0005_historicalnutrient_order_nutrient_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrient',
            options={'ordering': ['order']},
        ),
    ]
