# Generated by Django 4.2 on 2023-09-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purposes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purpose',
            options={'ordering': ['name']},
        ),
    ]
