# Generated by Django 4.1.7 on 2023-03-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0004_alter_flock_breed_type_alter_flock_hatch_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flock',
            name='hatch_date',
        ),
        migrations.RemoveField(
            model_name='historicalflock',
            name='hatch_date',
        ),
    ]
