# Generated by Django 4.1.7 on 2023-02-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=250, unique=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('is_double_yolk', models.BooleanField(default=False)),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('is_dead', models.BooleanField(default=False)),
                ('dead_date', models.DateField(blank=True, null=True)),
                ('breed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='breeds.breedtype')),
            ],
        ),
    ]
