# Generated by Django 4.1.7 on 2023-03-01 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_initial'),
        ('chickens', '0001_initial'),
        ('locations', '0001_initial'),
        ('flocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chicken',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='chicken',
            name='flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='chicken',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='locations.house'),
        ),
        migrations.AddField(
            model_name='chicken',
            name='layed_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.layedplace'),
        ),
    ]
