# Generated by Django 4.1.7 on 2023-02-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chickens', '0001_initial'),
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='farms.farm'),
        ),
    ]
