# Generated by Django 4.1.7 on 2023-02-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
        ('chickens', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='flock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='chicken',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='locations.house'),
        ),
        migrations.AddField(
            model_name='chicken',
            name='layed_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.layedplace'),
        ),
    ]
