# Generated by Django 4.1.7 on 2023-03-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0003_chicken_breed_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='egg_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
