# Generated by Django 4.1.7 on 2023-02-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
        ('breeds', '0001_initial'),
        ('locations', '0001_initial'),
        ('chickens', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='breed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='breeds.breedtype'),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='locations.house'),
        ),
    ]
