# Generated by Django 4.1.7 on 2023-03-07 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding_pairs', '0002_initial'),
        ('locations', '0003_historicalcountry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0004_alter_farm_city'),
        ('flocks', '0002_initial'),
        ('breeds', '0002_initial'),
        ('chickens', '0004_chicken_egg_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalChicken',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.CharField(db_index=True, max_length=250)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('is_double_yolk', models.BooleanField(default=False)),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('egg_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_dead', models.BooleanField(default=False)),
                ('dead_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('breed_pair', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='breeding_pairs.breedpair')),
                ('breed_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='breeds.breedtype')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='farms.farm')),
                ('flock', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flocks.flock')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.house')),
                ('layed_place', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.layedplace')),
            ],
            options={
                'verbose_name': 'historical chicken',
                'verbose_name_plural': 'historical chickens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
