# Generated by Django 4.1.7 on 2023-02-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('chickens', '0004_alter_chicken_breed_type_alter_chicken_farm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='layed_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.layedplace'),
        ),
    ]
