# Generated by Django 4.1.7 on 2023-03-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0005_historicalchicken'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='day_alive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='day_alive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
