# Generated by Django 4.1.7 on 2023-02-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0001_initial'),
        ('chickens', '0005_alter_chicken_layed_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='flocks.flock'),
        ),
    ]
