# Generated by Django 4.1.7 on 2023-03-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0006_chicken_day_alive_historicalchicken_day_alive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chicken',
            old_name='day_alive',
            new_name='days_alive',
        ),
        migrations.RenameField(
            model_name='historicalchicken',
            old_name='day_alive',
            new_name='days_alive',
        ),
    ]
