# Generated by Django 4.1.7 on 2023-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0007_rename_day_alive_chicken_days_alive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='days_alive',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='days_alive',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
