# Generated by Django 4.1.7 on 2023-03-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0008_alter_chicken_days_alive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='days_alive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='days_alive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
