# Generated by Django 4.1.7 on 2023-03-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0009_alter_chicken_days_alive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True),
        ),
    ]
