# Generated by Django 4.1.7 on 2023-03-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0010_alter_chicken_sex_alter_historicalchicken_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='pen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='pen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
