# Generated by Django 4.2 on 2023-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweight',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
