# Generated by Django 4.2 on 2024-02-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0002_alter_historicalweight_week_alter_weight_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweight',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True),
        ),
    ]
