# Generated by Django 4.2 on 2023-11-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0002_alter_historicalweight_weight_alter_weight_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalweight',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='weight_unit',
        ),
        migrations.AlterField(
            model_name='historicalweight',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
    ]
