# Generated by Django 4.2 on 2024-05-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0003_alter_historicalweight_weight_alter_weight_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-created_at']},
        ),
    ]
