# Generated by Django 4.2 on 2023-11-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0010_alter_chicken_pen_alter_historicalchicken_pen'),
        ('weights', '0003_remove_historicalweight_weight_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalweight',
            name='flock',
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('chicken', 'week')},
        ),
        migrations.RemoveField(
            model_name='weight',
            name='flock',
        ),
    ]
