# Generated by Django 4.2 on 2023-04-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='updated_at',
        ),
    ]
