# Generated by Django 4.1.5 on 2023-01-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='updated_at',
        ),
    ]
