# Generated by Django 4.1.5 on 2023-01-21 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0002_remove_farm_created_at_remove_farm_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
