# Generated by Django 4.1.5 on 2023-01-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0002_alter_user_managers_user_ate_joined_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
