# Generated by Django 4.1.5 on 2023-01-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0003_user_name_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', max_length=250),
        ),
    ]
