# Generated by Django 4.1.5 on 2023-01-22 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0007_alter_user_name_alter_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ate_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
