# Generated by Django 4.1.5 on 2023-01-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0013_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
