# Generated by Django 4.1.5 on 2023-01-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0018_chicken_chickenparent_egg_historicalegg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chickenstage',
            name='chicken',
        ),
        migrations.RemoveField(
            model_name='historicalchickenstage',
            name='chicken',
        ),
        migrations.AddField(
            model_name='chicken',
            name='chicken_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfm_api.chickenstage'),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='chicken_stage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pfm_api.chickenstage'),
        ),
    ]
