# Generated by Django 4.1.5 on 2023-02-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0018_breedtype_chicken_chickenparent_chickenstage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='week',
        ),
        migrations.RemoveField(
            model_name='historicalegg',
            name='week',
        ),
    ]
