# Generated by Django 4.1.5 on 2023-01-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0019_remove_chickenstage_chicken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfm_api.chickenparent'),
        ),
    ]
