# Generated by Django 4.1.5 on 2023-01-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0020_alter_chicken_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedtype',
            name='chicken',
        ),
        migrations.RemoveField(
            model_name='historicalbreedtype',
            name='chicken',
        ),
        migrations.AddField(
            model_name='chicken',
            name='breed_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfm_api.breedtype'),
        ),
        migrations.AddField(
            model_name='chicken',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfm_api.farm'),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='breed_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pfm_api.breedtype'),
        ),
        migrations.AddField(
            model_name='historicalchicken',
            name='farm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pfm_api.farm'),
        ),
    ]
