# Generated by Django 4.1.5 on 2023-01-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0021_remove_breedtype_chicken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallayedplace',
            name='egg',
        ),
        migrations.RemoveField(
            model_name='layedplace',
            name='egg',
        ),
        migrations.AddField(
            model_name='egg',
            name='layed_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfm_api.layedplace'),
        ),
        migrations.AddField(
            model_name='historicalegg',
            name='layed_place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pfm_api.layedplace'),
        ),
    ]
