# Generated by Django 4.1.5 on 2023-02-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0024_chicken_is_double_yolk_chicken_layed_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenprogress',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chicken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfm_api.chicken')),
            ],
        ),
        migrations.CreateModel(
            name='ChickenGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('chicken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfm_api.chicken')),
            ],
        ),
    ]
