# Generated by Django 4.1.5 on 2023-02-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0025_alter_chickenprogress_weight_eggproduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickengrowth',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickengrowth',
            name='chicken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth', to='pfm_api.chicken'),
        ),
    ]
