# Generated by Django 4.1.5 on 2023-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm_api', '0026_chickengrowth_week_alter_chickengrowth_chicken'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedtype',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalbreedtype',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
