version: '3.7'

networks:
  tpgs:
    driver: bridge

services:
  postgresql:
    image: tpgs/postgresql
    container_name: tpgs_postgresql
    build:
      context: .
      dockerfile: postgresql/Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
    volumes:
      - './postgresql/db:/var/lib/postgresql/data'
      - './postgresql/data:/mnt'
    ports:
      - '5432:5432'
  redis:
    image: tpgs/redis
    container_name: tpgs_redis
    build:
      context: .
      dockerfile: redis/Dockerfile
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    ports:
      - '6379:6379'