version: '3.7'

networks:
  odoo_modules:
    driver: bridge

services:
  postgresql:
    image: ilri_pfm/postgresql
    container_name: odoo_modules_postgresql
    build:
      context: .
      dockerfile: postgresql/Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
    volumes:
      - './postgresql/db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'