# Generated by Django 4.1.5 on 2023-02-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_breedtype_chicken_city_country_farm_feedtype_flock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farms',
            field=models.ManyToManyField(to='api.farm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
