# Generated by Django 4.1.5 on 2023-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_admin_user_is_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='hatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='layed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='hatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='layed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
