# Generated by Django 4.1.5 on 2023-02-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chicken_hatch_date_alter_chicken_layed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='dead_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='dead_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
