# Generated by Django 4.1.5 on 2023-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chicken_dead_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedpair',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbreedpair',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
