# Generated by Django 4.1.6 on 2023-02-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chicken_feedtype_weight_layedplace_historicalweight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='tag',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalchicken',
            name='tag',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
