# Generated by Django 4.1.5 on 2023-02-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_historicalflock_flock_chicken_flock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flocks', to='api.farm'),
        ),
        migrations.AddField(
            model_name='historicalflock',
            name='farm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.farm'),
        ),
    ]
