# Generated by Django 4.1.5 on 2023-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_flock_farm_historicalflock_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalweight',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='date',
        ),
        migrations.AddField(
            model_name='historicalweight',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weight',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
