# Generated by Django 4.1.5 on 2023-02-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_historicalweight_date_remove_weight_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalegg',
            name='date',
        ),
        migrations.AddField(
            model_name='egg',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='egg',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalegg',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalegg',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='breedtype',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='breed_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chickens', to='api.breedtype'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flock',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flock', to='api.farm'),
        ),
        migrations.AlterField(
            model_name='flock',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbreedtype',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historicalfeed',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalflock',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historicalweight',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
