# Generated by Django 4.1.7 on 2023-02-27 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chickens', '0006_alter_chicken_flock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='chickens.chicken')),
                ('sire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='chickens.chicken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
