# Generated by Django 4.1.7 on 2023-03-01 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeding_pairs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chickens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedpair',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breedpair',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='chickens.chicken'),
        ),
        migrations.AddField(
            model_name='breedpair',
            name='sire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='chickens.chicken'),
        ),
    ]
