# Generated by Django 4.2 on 2024-01-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryList',
            fields=[
                ('unique_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('farm_name', models.TextField()),
                ('farm_id', models.IntegerField()),
                ('hatchery_id', models.IntegerField()),
                ('hatchery_name', models.TextField()),
                ('house_id', models.IntegerField()),
                ('house_name', models.TextField()),
                ('pen_id', models.IntegerField()),
                ('pen_name', models.TextField()),
                ('breed_id', models.IntegerField()),
                ('breed_name', models.TextField()),
                ('generation', models.TextField()),
            ],
            options={
                'db_table': 'directory_list',
                'managed': False,
            },
        ),
    ]
