# Generated by Django 4.2 on 2024-03-17 12:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chickens', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryList',
            fields=[
                ('unique_id', models.CharField(
                    max_length=255, primary_key=True, serialize=False)),
                ('farm_name', models.TextField()),
                ('farm_id', models.IntegerField()),
                ('hatchery_id', models.IntegerField()),
                ('hatchery_name', models.TextField()),
                ('house_id', models.IntegerField()),
                ('house_name', models.TextField()),
                ('pen_id', models.IntegerField()),
                ('pen_name', models.TextField()),
                ('breed_id', models.IntegerField()),
                ('breed_name', models.TextField()),
                ('generation', models.TextField()),
            ],
            options={
                'db_table': 'directory_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChickenRecordset',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('week', models.PositiveIntegerField(default=0, validators=[
                 django.core.validators.MinValueValidator(0)])),
                ('feed_weight', models.DecimalField(blank=True,
                 decimal_places=3, default=0, max_digits=16, null=True)),
                ('body_weight', models.DecimalField(blank=True,
                 decimal_places=3, default=0, max_digits=16, null=True)),
                ('no_eggs', models.IntegerField(blank=True, null=True)),
                ('eggs_weight', models.DecimalField(blank=True,
                 decimal_places=3, default=0, max_digits=16, null=True)),
                ('chicken', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='chickens.chicken')),
            ],
            options={
                'db_table': 'chicken_recordset',
            },
        ),
        migrations.RunSQL(
            """
                CREATE OR REPLACE VIEW chicken_recordset AS
                    SELECT row_number() OVER () AS id,
                        cc.id AS chicken_id, COALESCE(jj.week, 0) as week,
                        jj.feed_weight, jj.body_weight,
                        jj.no_eggs, jj.eggs_weight
                        FROM 
                        (
                            SELECT 
                                COALESCE(COALESCE(ww.chicken_id, ff.chicken_id), ee.chicken_id) AS chicken_id,
                                ww.week AS ww_week, ff.week AS ff_week, ee.week AS ee_week,
                                coalesce(COALESCE(COALESCE(ww.week, ff.week), ee.week), 0) AS week,
                                ww.id AS body_weight_id, ww.weight AS body_weight,
                                ee.id AS egg_id, ee.eggs AS no_eggs, ee.weight AS eggs_weight,
                                ff.id AS feed_id, ff.weight AS feed_weight
                            FROM weights_weight ww
                            FULL JOIN eggs_egg ee
                                ON ee.week = ww.week AND ee.chicken_id = ww.chicken_id
                            FULL JOIN feeds_feed ff
                                ON ff.week = ww.week AND ff.chicken_id = ee.chicken_id
                        ) jj
                    FULL JOIN chickens_chicken cc
                       on cc.id = jj.chicken_id
                    order by week;
            """,
            """DROP VIEW chicken_recordset"""
        )
    ]
