# Generated by Django 4.2 on 2024-02-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chickenranking',
            options={'managed': False},
        ),
    ]
