# Generated by Django 4.2 on 2024-04-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chickenrecordset',
            options={'managed': False},
        ),
    ]
