# Generated by Django 4.2 on 2024-02-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_alter_chickenranking_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chickenranking',
            table='chicken_ranking',
        ),
    ]
