# Generated by Django 4.2 on 2023-05-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RationIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_type', models.CharField(choices=[('RQ', 'Requirement'), ('RA', 'Ration'), ('IN', 'Ingredient')], default='IN', max_length=2)),
                ('dm', models.FloatField()),
                ('me', models.FloatField()),
                ('cp', models.FloatField()),
                ('lys', models.FloatField()),
                ('meth', models.FloatField()),
                ('mc', models.FloatField()),
                ('ee', models.FloatField()),
                ('cf', models.FloatField()),
                ('ca', models.FloatField()),
                ('p', models.FloatField()),
                ('ratio_min', models.FloatField()),
                ('ratio_max', models.FloatField()),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='rations.ration')),
            ],
        ),
    ]
