# Generated by Django 4.2 on 2023-05-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationingredient',
            name='ca',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='cf',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='cp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='dm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='ee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='lys',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='mc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='me',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='meth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='p',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='ratio_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rationingredient',
            name='ratio_min',
            field=models.FloatField(null=True),
        ),
    ]
