# Generated by Django 4.1.7 on 2023-04-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farm_city'),
        ('hatchery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchery',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hatchery', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='historicalhatchery',
            name='farm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='farms.farm'),
        ),
    ]
