# Generated by Django 4.1.7 on 2023-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0002_hatchery_farm_historicalhatchery_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincubation',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incubation',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
