# Generated by Django 4.2 on 2023-10-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0010_alter_formula_desired_dm_alter_formula_desired_ratio_and_more'),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='formula',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formulas.formula'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeed',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
