# Generated by Django 4.2 on 2024-01-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pen', '0001_initial'),
        ('feeds', '0001_initial'),
        ('formulas', '0001_initial'),
        ('chickens', '0002_initial'),
        ('hatchery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfeed',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='formula',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='hatchery',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='pen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pen.pen'),
        ),
        migrations.AddField(
            model_name='feed',
            name='chicken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='chickens.chicken'),
        ),
        migrations.AddField(
            model_name='feed',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='feed',
            name='hatchery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='feed',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feed',
            name='pen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='pen.pen'),
        ),
    ]
