# Generated by Django 4.2 on 2023-10-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
        ('flocks', '0007_remove_flockaccusation_no_chicken_and_more'),
        ('chickens', '0005_chicken_reduction_date_chicken_reduction_reason_and_more'),
        ('feeds', '0002_feed_formula_historicalfeed_formula_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feed',
            name='pen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='pen.pen'),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='pen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pen.pen'),
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('flock', 'pen', 'chicken', 'week')},
        ),
    ]
