# Generated by Django 4.2 on 2024-02-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_feed_week_alter_historicalfeed_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeed',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True),
        ),
    ]
