# Generated by Django 4.2 on 2023-10-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_feed_unique_together_feed_pen_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set(),
        ),
    ]
