# Generated by Django 4.2 on 2023-11-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0003_historicalhatcheryegg'),
        ('feeds', '0004_alter_feed_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='historicalfeed',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='historicalfeed',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='feed',
            name='hatchery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='hatchery.hatchery'),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='hatchery',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hatchery.hatchery'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeed',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
    ]
