# Generated by Django 4.2 on 2024-03-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_feed_weight_alter_historicalfeed_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-created_at']},
        ),
    ]
