# Generated by Django 4.2 on 2024-05-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0004_alter_chicken_color_alter_historicalchicken_color'),
        ('feeds', '0005_alter_feed_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('chicken', 'week')},
        ),
    ]
