# Generated by Django 4.2 on 2023-11-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_remove_feed_flock_remove_feed_weight_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='historicalfeed',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='feeds.feed'),
        ),
    ]
