# Generated by Django 4.2 on 2023-05-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ca',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cf',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cp',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dm',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ee',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='lys',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='mc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='me',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='meth',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='p',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ratio_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ratio_min',
            field=models.FloatField(default=0, null=True),
        ),
    ]
