# Generated by Django 4.2 on 2023-06-07 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0002_alter_nutrient_description_and_more'),
        ('units', '0001_initial'),
        ('ingredients', '0007_alter_ingredient_ca_alter_ingredient_cf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='cf',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='dm',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ee',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='lys',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='mc',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='me',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='meth',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='p',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ratio_max',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ratio_min',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='units.unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='ingredients.ingredienttype'),
        ),
        migrations.CreateModel(
            name='IngredientNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrients',
            field=models.ManyToManyField(through='ingredients.IngredientNutrient', to='nutrients.nutrient'),
        ),
    ]
