# Generated by Django 4.2 on 2023-06-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_remove_ingredient_ca_remove_ingredient_cf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ManyToManyField(related_name='ingredients', to='ingredients.ingredienttype'),
        ),
    ]
