# Generated by Django 4.2 on 2023-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_alter_ingredient_ingredient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='ingredients.ingredienttype'),
        ),
    ]
