# Generated by Django 4.2 on 2023-06-19 18:36

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_alter_ingredient_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='ETB', max_digits=14, null=True),
        ),
    ]
