# Generated by Django 4.2 on 2023-08-02 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_rename_ratio_unitconverter_factor_and_more'),
        ('ingredients', '0012_alter_ingredient_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='dm',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_unit',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='units.unit'),
        ),
    ]
