# Generated by Django 4.2 on 2023-08-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_ingredient_dm_alter_ingredient_price_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True),
        ),
    ]
