# Generated by Django 4.2 on 2023-10-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_alter_ingredient_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price_unit',
        ),
    ]
