# Generated by Django 4.2 on 2023-10-13 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0016_remove_ingredient_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientnutrient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientnutrient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredientnutrient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
