# Generated by Django 4.2 on 2023-11-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0004_nutrient_created_at_nutrient_created_by_and_more'),
        ('ingredients', '0018_historicalingredienttype_historicalingredient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientnutrient',
            unique_together={('ingredient', 'nutrient')},
        ),
    ]
