# Generated by Django 4.2 on 2023-11-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0020_historicalingredientnutrient'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='ingredient_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingredients.ingredienttype'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_type',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='ingredients.ingredienttype'),
        ),
    ]
