# Generated by Django 4.2 on 2023-11-21 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0021_historicalingredient_ingredient_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
