# Generated by Django 4.2 on 2023-12-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0022_historicalingredient_max_historicalingredient_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalingredient',
            name='max',
        ),
        migrations.RemoveField(
            model_name='historicalingredient',
            name='min',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='max',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='min',
        ),
    ]
