export { default } from "next-auth/middleware";
export const config = {
  matcher: [
    "/dashboard/:path*",
    "/chickens/:path*",
    "/pen/:path*",
    "/breeds/:path*",
    "/cities/:path*",
    "/countries/:path*",
    "/eggs/:path*",
    "/farms/:path*",
    "/feeds/:path*",
    "/flocks/:path*",
    "/formulation/:path*",
    "/houses/:path*",
    "/help/:path*",
    "/hhep/:path*",
    "/ingredient-types/:path*",
    "/ingredients/:path*",
    "/invitations/:path*",
    "/nutrient-groups/:path*",
    "/nutrients/:path*",
    "/purposes/:path*",
    "/setting/:path*",
    "/unit-converters/:path*",
    "/units/:path*",
    "/users/:path*",
    "/weights/:path*",
  ],
};
