# Generated by Django 4.2 on 2023-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='historicalegg',
            name='weight_unit',
        ),
        migrations.AlterField(
            model_name='egg',
            name='eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='egg',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalegg',
            name='eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalegg',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
