# Generated by Django 4.2 on 2023-11-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0008_chicken_hatch_date_historicalchicken_hatch_date'),
        ('eggs', '0002_remove_egg_weight_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalegg',
            name='flock',
        ),
        migrations.AlterUniqueTogether(
            name='egg',
            unique_together={('chicken', 'week')},
        ),
        migrations.RemoveField(
            model_name='egg',
            name='flock',
        ),
    ]
