# Generated by Django 4.2 on 2024-02-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0003_alter_egg_week_alter_historicalegg_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalegg',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=16, null=True),
        ),
    ]
