# Generated by Django 4.2 on 2024-05-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0004_alter_egg_weight_alter_historicalegg_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egg',
            options={'ordering': ['-created_at']},
        ),
    ]
