# Generated by Django 4.1.7 on 2023-02-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farms',
            field=models.ManyToManyField(to='farms.farm'),
        ),
    ]
