# Generated by Django 4.2 on 2024-01-20 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('expire_date', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('farms', models.ManyToManyField(to='farms.farm')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
