# Generated by Django 4.2 on 2023-08-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expire_date',
            field=models.DateTimeField(),
        ),
    ]
