# Generated by Django 4.2 on 2023-08-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_historicalfarm'),
        ('invitations', '0003_invitation_farms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='farms',
        ),
        migrations.AddField(
            model_name='invitation',
            name='farms',
            field=models.ManyToManyField(to='farms.farm'),
        ),
    ]
