# Generated by Django 4.2 on 2023-09-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_remove_invitation_farms_invitation_farms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-sent_date']},
        ),
    ]
